#!/bin/bash

#$ -M EMAIL
#$ -m n
#$ -pe mpi-16 64
#$ -q *@@richter
#$ -N case1
#$ -j y


module load mvapich2
module load intel
module load netcdf

case=case1
time=0000000
runout=$case.out.$time

datadir=/scratch365/NETID/NTLP-wavy/$case
homedir=~/NTLP-wavy/$case

cd $homedir

imachine=0
echo $imachine > ./mach.file
echo $datadir >> ./mach.file

mpirun -n 64 $homedir/../lesmpi.a $homedir/params.in > $datadir/$runout

