#!/bin/bash

case=$(basename $(pwd))
parent=$(basename $(dirname $(pwd)))

if [[ $(hostname) == cheyenne* ]]; then
  datadir=/glade/scratch/$USER/$parent/$case
else
  datadir=/scratch365/$USER/$parent/$case
fi

rm -v $datadir/*
rm -v ${case}_* fort.1 mach.file
